### ISSUE TITLE
Warn (or solve) if there are duplicate child class field names

### ISSUE THREAD

**Issue by KrzysiekJ** [craigds/django-typed-models#8]
This issue is a copy of KrzysiekJ/django-typed-models#1 by @mnieber.

The following does not work because the name "request_message" is duplicated in two child classes of the base class Message, which produces a conflict later on when querying the database.

``` python
class Message(TypedModel):
    pass

class AcceptMessage(Message):
    request_message = models.ForeignKey('self', null=True, blank=True, related_name='+')

class DeclineMessage(Message):
    request_message = models.ForeignKey('self', null=True, blank=True, related_name='+')
```

This can be solved by moving request_message to the base class but this is not always what you want (perhaps a third class inheriting from Message does not have a request_message field).

It would be nice if TypedModel would at least raise an exception in this case so that the programmer becomes aware of the problem.

**Comment by craigds** [comment]
Long time no speak, but since 2013 django's grown a reliable field serialisation and comparison scheme (for migrations) so this should be perfectly doable now.

If we find two fields exactly the same we can amalgamate them, and if they're different in any way but have the same name we can throw an error.
